<?php
$this->headTitle('Manage Author');

$this->mainMenu()->setActiveItemId('author');

$this->pageBreadcrumbs()->setItems(['Author'=>$this->url('home')]);

echo $this->flashMessenger()->render();
?>

<h1>Manage Authors</h1>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Status</th>
    </tr>
    
    <?php foreach ($authors as $author): ?>
    
    <tr>
        <td><?= $this->escapeHtml($author->getId()); ?></td>
        <td>
            <a href="<?= $this->url('author-show', ['action'=>'show', 'id'=>$author->getId()]); ?>">
                <?= $this->escapeHtml($author->getName()); ?>
            </a> 
        </td>
        <td><?= $this->escapeHtml($author->getEmail()); ?></td>
        <td><?= $this->escapeHtml($authorManager->getAuthorStatusAsString($author)); ?></td>
    </tr>
        
    <?php endforeach; ?>   
    
</table>